require "rails/railtie"
require "action_controller/metal/strong_parameters"

module Railcutters
  class Railtie < ::Rails::Railtie
    initializer "railcutters.load_action_controller" do
      next unless config.railcutters.use_params_renamer

      ::ActionController::Parameters.include(ActionController::ParamsRenamer)
    end

    initializer "railcutters.load_sqlite_sensible_defaults" do
      next unless config.railcutters.use_sqlite_better_defaults

      ActiveSupport.on_load(:active_record_sqlite3adapter) do
        # self refers to `SQLite3Adapter` here, so we can call .include directly
        include(ActiveRecord::ConnectionAdapters::SQLite3Adapter)
      end

      # Configures SQLite with a strict strings mode, which disables double-quoted string literals.
      config.sqlite3_adapter_strict_strings_by_default = true
      # Allow us to use sqlite3 in production without warnings
      config.active_record.sqlite3_production_warning = false
    end

    initializer "railcutters.load_active_record" do
      next unless config.railcutters.active_record_enum_defaults.present?

      ::ActiveRecord::Base.extend(ActiveRecord::EnumDefaults)
    end

    # Settings to allow us to turn individual features on and off
    # ===========================================================

    config.railcutters = ActiveSupport::OrderedOptions.new

    # Enable loading the params renamer, and allows parameters renaming from within controllers
    # using an easy syntax
    config.railcutters.use_params_renamer = true

    # Use sensible SQLite3 defaults such as enabling WAL and strict mode.
    config.railcutters.use_sqlite_better_defaults = true

    # Use better defaults for ActiveRecord::Enum. Pass nil or an empty hash to use Rails' defaults.
    #
    # WARNING: this will affect existing code that uses `enum`, so you should only enable this if
    # you're starting a new project or are willing to change your existing code.
    config.railcutters.active_record_enum_defaults = {
      # Keeping a prefix for all methods generated by a enum is a good idea to avoid conflicts
      prefix: true,

      # New in Rails 7.1: Instead of raising an error when an invalid value is passed to an enum, it
      # validates the value and adds an error to the record instead
      validate: { allow_nil: true },

      # Both these options below are the Rails' defaults, but we're setting them explicitly here for
      # clarity's sake
      instance_methods: true,
      scopes: true
    }

    # This will convert any array passed as the second argument to ActiveRecord::Enum to a hash,
    # being the same value for both the key and the value. This is useful when you want to use
    # string values for your enums, but don't want to repeat yourself.
    # The official Rails' documentations says that this will likely lead to slower database queries,
    # but it's a tradeoff worth making in most cases for a better developer experience.
    #
    # WARNING: this will affect existing code that uses `enum`, so you should only enable this if
    # you're starting a new project or are willing to change your existing code.
    config.railcutters.active_record_enum_use_string_values = true

    # This is a helper method to set all the defaults to a safe value, meaning that it will not make
    # any changes to the default behavior of Rails. This is useful if you are installing this gem
    # in an existing project and don't want to change any default behavior.
    config.railcutters.define_singleton_method(:set_safe_defaults!) do
      self.active_record_enum_defaults = nil
      self.active_record_enum_use_string_values = false
      self.use_sqlite_better_defaults = false
    end
  end
end
