require_relative "railcutters/version"
require_relative "railcutters/action_controller/params_renamer"
require_relative "railcutters/active_record/enum_defaults"
require_relative "railcutters/active_record/connection_adapters/sqlite3_adapter"
require_relative "railcutters/active_record/schema_definitions"
require_relative "railcutters/railtie"
